name: Main

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate README
        run: ./bin/generate-readme.js

      - name: Commit generated README
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          commit_message: Update README
          branch: main
          commit_user_name: teimurjan-bot 🤖
          commit_user_email: actions@github.com
          commit_author: teimurjan-bot 🤖 <actions@github.com>
